name: workflow1
on:
    workflow_dispatch:
   
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            -uses: actions/checkout@v2
            -name: run sag-hallo
             run: sag-hallo.bat
             shell: cmd