name: workflow1
on:
    workflow_dispatch:
   
jobs:
    example-job:
        steps:
            - run: npm install -g bats
    print:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: run sag-hallo
              run: ./.sag-hallo.bat
              shell: cmd